import { title } from "process";

const cardData=[
    {
        title:"Total Households Inteviewed",
        value: 3000,
        description: "Total households visited",
        tooltip: "Total households visited"
    },
    {
        title: "Total individuals interviewed",
        value: 1500,
        description: "Total individuals interviewed today",
        tooltip: "Total individuals interviewed today"
    },
    {
        title: "Households with Errors",
        value: 2000,
        description: "Households data with Errors",
        tooltip: "Households data with Errors"
    },
    {
        title: "Individuals with Missing Data",
        value: 1000,
        description: "Individuals with missing data",
        tooltip: "Individuals with missing data"
    }
]
const householdData = [
    {
      number: 1,
      head: "Waiswa Philip",
      location: "Iganga",
      country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
    },
    {
        number: 2,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 3,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 4,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 5,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 6,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 7,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 8,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 9,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 10,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 11,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
      number: 12,
      head: "Waiswa Philip",
      location: "Iganga",
      country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
    },
    {
      number: 13,
      head: "Waiswa Philip",
      location: "Iganga",
      country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
    },{
        number: 14,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
      {
        number: 15,
        head: "Waiswa Philip",
        location: "Iganga",
        country: "Uganda",
      region: "Busoga",
      subregion: "Busoga",
      healthregion: "Busoga",
      tribe: "Musoga",
      teamnumber: "0089",
      teamlead: "Philip Waiswa",
      subcounty: "Bulamagi",
      parish: "Bukoyo",
      village: "Bukoyo"
      },
  ]
export {cardData, householdData}